In [1]:
from absenteeism_module import *

In [3]:
pd.read_csv("Absenteeism_new_data.csv")

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

In [5]:
model=absenteeism_model('model','scaler')

In [7]:
model.load_and_clean_data("Absenteeism_new_data.csv")

In [9]:
df_new=model.predicted_outputs()
df_new

,Reason_1,Reason_2,Reason_3,Reason_4,Month_value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,False,0.0,False,True,6,179,30,19,1,0,0,0.135951,0
1,True,0.0,False,False,6,361,28,27,0,1,4,0.852483,1
2,False,0.0,False,True,6,155,34,25,0,2,0,0.271552,0
3,False,0.0,False,True,6,179,40,22,1,2,0,0.204150,0
4,True,0.0,False,False,6,155,34,25,0,2,0,0.721718,1
5,True,0.0,False,False,6,225,28,24,0,1,2,0.703326,1
6,True,0.0,False,False,6,118,46,25,0,2,0,0.539066,1
7,False,0.0,False,True,6,179,30,19,1,0,0,0.135951,0
8,False,0.0,False,True,6,118,37,28,0,0,0,0.129728,0
9,True,0.0,False,False,6,118,37,28,0,0,0,0.509098,1
10,False,0.0,False,True,6,378,36,21,0,2,4,0.399400,0
11,False,0.0,True,False,6,118,50,31,0,1,0,0.604656,1
12,False,0.0,True,False,6,233,31,21,1,1,8,0.294564,0
13,False,0.0,False,True,6,179,30,19,1,0,0,0.135951,0
14,False,0.0,False,False,6,235,48,33,0,1,5,0.054136,0
15,False,0.0,False,False,6,268,33,25,1,0,0,0.164388,0
16,False,0.0,True,False,6,118,50,31,0,1,0,0.604656,1
17,True,0.0,False,False,6,179,30,19,1,0,0,0.522591,1
18,False,0.0,False,True,6,291,40,25,0,1,1,0.358633,0
19,True,0.0,False,False,7,179,30,19,1,0,0,0.532207,1
20,False,0.0,False,True,7,118,37,28,0,0,0,0.134146,0
21,False,0.0,False,True,7,233,31,21,1,1,8,0.042219,0
22,True,0.0,False,False,7,118,37,28,0,0,0,0.518735,1
23,True,0.0,False,False,7,118,37,28,0,0,0,0.518735,1
24,False,0.0,False,True,7,233,31,21,1,1,8,0.042219,0
25,False,0.0,False,True,7,235,43,38,0,1,0,0.497581,0
26,False,0.0,True,False,7,233,31,21,1,1,8,0.302644,0
27,True,0.0,False,False,7,228,58,22,0,2,1,0.565503,1
28,False,0.0,False,True,7,118,37,28,0,0,0,0.134146,0
29,True,0.0,False,False,7,228,58,22,0,2,1,0.565503,1
30,False,0.0,False,True,7,189,33,25,0,2,2,0.239112,0
31,False,0.0,False,True,7,118,37,28,0,0,0,0.134146,0
32,False,0.0,False,True,7,361,28,27,0,1,4,0.463323,0
33,False,0.0,False,True,7,225,28,24,0,1,2,0.261537,0
34,True,0.0,False,False,7,369,31,25,0,3,0,0.967738,1
35,True,0.0,False,False,7,289,33,30,0,2,1,0.910319,1
36,True,0.0,False,False,7,235,37,29,1,1,1,0.751601,1
37,False,0.0,False,False,7,118,40,34,0,1,8,0.012606,0
38,False,0.0,False,False,7,231,39,35,0,2,2,0.230016,0
39,False,0.0,False,False,7,179,53,25,0,1,1,0.049746,0

In [11]:
import pymysql

In [13]:
conn=pymysql.connect(database='predicted_outputs',user='root',password='MySQL6769#')

In [15]:
cursor=conn.cursor()

In [17]:
# Exceute
cursor.execute('SELECT * FROM predicted_outputs;')
#no data available so it shows 0

0

In [19]:
#now inserting values from csv to database
insert_query="INSERT INTO predicted_outputs VALUES"

In [21]:
df_new.shape

(40, 13)

In [23]:
df_new["Age"]

0     30
1     28
2     34
3     40
4     34
5     28
6     46
7     30
8     37
9     37
10    36
11    50
12    31
13    30
14    48
15    33
16    50
17    30
18    40
19    30
20    37
21    31
22    37
23    37
24    31
25    43
26    31
27    58
28    37
29    58
30    33
31    37
32    28
33    28
34    31
35    33
36    37
37    40
38    39
39    53
Name: Age, dtype: int64

In [25]:
for i in range(df_new.shape[0]):
    insert_query+= "("
    for j in range(df_new.shape[1]):
        insert_query+=str(df_new[df_new.columns.values[j]][i])+','
    insert_query=insert_query[:-1]+'),'

In [27]:
insert_query

'INSERT INTO predicted_outputs VALUES(False,0.0,False,True,6,179,30,19,1,0,0,0.1359507134221299,0),(True,0.0,False,False,6,361,28,27,0,1,4,0.8524830871236242,1),(False,0.0,False,True,6,155,34,25,0,2,0,0.2715520374211361,0),(False,0.0,False,True,6,179,40,22,1,2,0,0.2041498177527053,0),(True,0.0,False,False,6,155,34,25,0,2,0,0.7217183448557323,1),(True,0.0,False,False,6,225,28,24,0,1,2,0.703325518329062,1),(True,0.0,False,False,6,118,46,25,0,2,0,0.5390661588502895,1),(False,0.0,False,True,6,179,30,19,1,0,0,0.1359507134221299,0),(False,0.0,False,True,6,118,37,28,0,0,0,0.12972769175370605,0),(True,0.0,False,False,6,118,37,28,0,0,0,0.5090977529724466,1),(False,0.0,False,True,6,378,36,21,0,2,4,0.39939954780493686,0),(False,0.0,True,False,6,118,50,31,0,1,0,0.6046562602432249,1),(False,0.0,True,False,6,233,31,21,1,1,8,0.2945638442862153,0),(False,0.0,False,True,6,179,30,19,1,0,0,0.1359507134221299,0),(False,0.0,False,False,6,235,48,33,0,1,5,0.0541364723771123,0),(False,0.0,False,False,6,268,33,25,1,0,0,0.164388025027687,0),(False,0.0,True,False,6,118,50,31,0,1,0,0.6046562602432249,1),(True,0.0,False,False,6,179,30,19,1,0,0,0.5225911636882523,1),(False,0.0,False,True,6,291,40,25,0,1,1,0.3586330924247411,0),(True,0.0,False,False,7,179,30,19,1,0,0,0.5322073292344285,1),(False,0.0,False,True,7,118,37,28,0,0,0,0.1341460789811251,0),(False,0.0,False,True,7,233,31,21,1,1,8,0.04221911098006358,0),(True,0.0,False,False,7,118,37,28,0,0,0,0.5187354116935755,1),(True,0.0,False,False,7,118,37,28,0,0,0,0.5187354116935755,1),(False,0.0,False,True,7,233,31,21,1,1,8,0.04221911098006358,0),(False,0.0,False,True,7,235,43,38,0,1,0,0.49758083187148916,0),(False,0.0,True,False,7,233,31,21,1,1,8,0.302644012999436,0),(True,0.0,False,False,7,228,58,22,0,2,1,0.5655029217013533,1),(False,0.0,False,True,7,118,37,28,0,0,0,0.1341460789811251,0),(True,0.0,False,False,7,228,58,22,0,2,1,0.5655029217013533,1),(False,0.0,False,True,7,189,33,25,0,2,2,0.23911246326827904,0),(False,0.0,False,True,7,118,37,28,0,0,0,0.1341460789811251,0),(False,0.0,False,True,7,361,28,27,0,1,4,0.4633231573816241,0),(False,0.0,False,True,7,225,28,24,0,1,2,0.2615365463964359,0),(True,0.0,False,False,7,369,31,25,0,3,0,0.9677383086471781,1),(True,0.0,False,False,7,289,33,30,0,2,1,0.9103185079254614,1),(True,0.0,False,False,7,235,37,29,1,1,1,0.7516006918346253,1),(False,0.0,False,False,7,118,40,34,0,1,8,0.012606154921998219,0),(False,0.0,False,False,7,231,39,35,0,2,2,0.23001559203091707,0),(False,0.0,False,False,7,179,53,25,0,1,1,0.04974581355803781,0),'

In [29]:
insert_query=insert_query[:-1]+";"

In [31]:
insert_query

'INSERT INTO predicted_outputs VALUES(False,0.0,False,True,6,179,30,19,1,0,0,0.1359507134221299,0),(True,0.0,False,False,6,361,28,27,0,1,4,0.8524830871236242,1),(False,0.0,False,True,6,155,34,25,0,2,0,0.2715520374211361,0),(False,0.0,False,True,6,179,40,22,1,2,0,0.2041498177527053,0),(True,0.0,False,False,6,155,34,25,0,2,0,0.7217183448557323,1),(True,0.0,False,False,6,225,28,24,0,1,2,0.703325518329062,1),(True,0.0,False,False,6,118,46,25,0,2,0,0.5390661588502895,1),(False,0.0,False,True,6,179,30,19,1,0,0,0.1359507134221299,0),(False,0.0,False,True,6,118,37,28,0,0,0,0.12972769175370605,0),(True,0.0,False,False,6,118,37,28,0,0,0,0.5090977529724466,1),(False,0.0,False,True,6,378,36,21,0,2,4,0.39939954780493686,0),(False,0.0,True,False,6,118,50,31,0,1,0,0.6046562602432249,1),(False,0.0,True,False,6,233,31,21,1,1,8,0.2945638442862153,0),(False,0.0,False,True,6,179,30,19,1,0,0,0.1359507134221299,0),(False,0.0,False,False,6,235,48,33,0,1,5,0.0541364723771123,0),(False,0.0,False,False,6,268,33,25,1,0,0,0.164388025027687,0),(False,0.0,True,False,6,118,50,31,0,1,0,0.6046562602432249,1),(True,0.0,False,False,6,179,30,19,1,0,0,0.5225911636882523,1),(False,0.0,False,True,6,291,40,25,0,1,1,0.3586330924247411,0),(True,0.0,False,False,7,179,30,19,1,0,0,0.5322073292344285,1),(False,0.0,False,True,7,118,37,28,0,0,0,0.1341460789811251,0),(False,0.0,False,True,7,233,31,21,1,1,8,0.04221911098006358,0),(True,0.0,False,False,7,118,37,28,0,0,0,0.5187354116935755,1),(True,0.0,False,False,7,118,37,28,0,0,0,0.5187354116935755,1),(False,0.0,False,True,7,233,31,21,1,1,8,0.04221911098006358,0),(False,0.0,False,True,7,235,43,38,0,1,0,0.49758083187148916,0),(False,0.0,True,False,7,233,31,21,1,1,8,0.302644012999436,0),(True,0.0,False,False,7,228,58,22,0,2,1,0.5655029217013533,1),(False,0.0,False,True,7,118,37,28,0,0,0,0.1341460789811251,0),(True,0.0,False,False,7,228,58,22,0,2,1,0.5655029217013533,1),(False,0.0,False,True,7,189,33,25,0,2,2,0.23911246326827904,0),(False,0.0,False,True,7,118,37,28,0,0,0,0.1341460789811251,0),(False,0.0,False,True,7,361,28,27,0,1,4,0.4633231573816241,0),(False,0.0,False,True,7,225,28,24,0,1,2,0.2615365463964359,0),(True,0.0,False,False,7,369,31,25,0,3,0,0.9677383086471781,1),(True,0.0,False,False,7,289,33,30,0,2,1,0.9103185079254614,1),(True,0.0,False,False,7,235,37,29,1,1,1,0.7516006918346253,1),(False,0.0,False,False,7,118,40,34,0,1,8,0.012606154921998219,0),(False,0.0,False,False,7,231,39,35,0,2,2,0.23001559203091707,0),(False,0.0,False,False,7,179,53,25,0,1,1,0.04974581355803781,0);'

In [33]:
cursor.execute(insert_query)

40

In [35]:
conn.commit()

In [37]:
conn.close()

In [41]:
age=df_new["Age"].value_counts()
age

Age
37    8
30    5
31    5
28    4
40    3
33    3
34    2
50    2
58    2
46    1
36    1
48    1
43    1
39    1
53    1
Name: count, dtype: int64